#!/bin/bash
# init-manifest-branch.sh
# マニフェスト履歴管理用ブランチを初期化するスクリプト
#
# 使用方法:
#   chmod +x script/init-manifest-branch.sh
#   ./script/init-manifest-branch.sh
#
# または Git Bash / WSL で実行:
#   bash script/init-manifest-branch.sh

set -e

BRANCH_NAME="docs-manifest-history"

echo "🔧 マニフェスト履歴ブランチを初期化します..."

# 現在のブランチを保存
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "📍 現在のブランチ: $CURRENT_BRANCH"

# ブランチが既に存在するか確認
if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
    echo "⚠️ ブランチ '$BRANCH_NAME' は既に存在します"
    echo "   削除してから再実行する場合:"
    echo "   git branch -D $BRANCH_NAME"
    echo "   git push origin --delete $BRANCH_NAME"
    exit 1
fi

# リモートにブランチが存在するか確認
if git ls-remote --exit-code --heads origin $BRANCH_NAME >/dev/null 2>&1; then
    echo "⚠️ リモートにブランチ '$BRANCH_NAME' が既に存在します"
    echo "   削除してから再実行する場合:"
    echo "   git push origin --delete $BRANCH_NAME"
    exit 1
fi

# Orphanブランチを作成
echo "🌱 Orphanブランチ '$BRANCH_NAME' を作成中..."
git checkout --orphan $BRANCH_NAME

# 全ファイルをステージングから削除
git rm -rf . --quiet 2>/dev/null || true

# READMEとマニフェストファイルを作成
echo "# Manifest History Branch

このブランチはドキュメント差分検出用のマニフェストファイルを管理しています。

## 目的

- メインブランチにマニフェスト更新コミットを混入させない
- ドキュメント更新履歴を独立したブランチで追跡
- CI/CDでの自動コミット・プッシュを簡素化

## ファイル

- \`docs-manifest.yml\`: ドキュメントのハッシュと更新日時を記録

## 注意事項

- このブランチは直接編集しないでください
- GitHub Actionsによって自動更新されます

## 関連ドキュメント

- [設計書](../script/DESIGN_MANIFEST_BRANCH.md)
" > README.md

# 空のマニフェストファイルを作成
echo "# Document Manifest - Auto-generated by GitHub Actions
# Do not edit manually
" > docs-manifest.yml

# コミット
git add README.md docs-manifest.yml
git commit -m "🎉 Initialize manifest history branch"

# リモートにプッシュ
echo "🚀 リモートにプッシュ中..."
git push -u origin $BRANCH_NAME

# 元のブランチに戻る
echo "🔙 元のブランチに戻ります: $CURRENT_BRANCH"
git checkout $CURRENT_BRANCH

echo ""
echo "✅ 完了！"
echo ""
echo "📋 次のステップ:"
echo "   1. deploy.yml と notify-and-vectorize.mjs の変更をコミット"
echo "   2. masterブランチにマージしてデプロイをテスト"
echo ""
