name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  update-embeddings:
    name: Update Article Embeddings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 履歴を2つ前まで取得

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install pro dependencies
        working-directory: pro
        run: npm ci

      - name: Install script dependencies
        working-directory: script
        run: npm ci

      - name: Run vectorization script
        working-directory: script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REACT_APP_GEMINI_API_KEY: ${{ secrets.REACT_APP_GEMINI_API_KEY }}
          HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}
        run: node vectorize_articles.mjs

  build:
    name: Build Docusaurus Site and Generate Candidate Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Clear npm cache
        working-directory: pro
        run: npm cache clean --force

      - name: Remove Docusaurus cache
        working-directory: pro
        run: rm -rf .docusaurus

      - name: Install dependencies
        working-directory: pro
        run: npm ci

      - name: Clear Docusaurus cache
        working-directory: pro
        run: npm run clear

      - name: Inject env vars for frontend
        working-directory: pro
        run: |
          echo "REACT_APP_GEMINI_API_KEY=${{ secrets.REACT_APP_GEMINI_API_KEY }}" > .env
          echo "REACT_APP_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> .env
          echo "DOCSEARCH_APP_ID=${{ secrets.DOCSEARCH_APP_ID }}" >> .env
          echo "DOCSEARCH_API_KEY=${{ secrets.DOCSEARCH_API_KEY }}" >> .env
          echo "DOCSEARCH_INDEX_NAME=${{ secrets.DOCSEARCH_INDEX_NAME }}" >> .env

      - name: Build Docusaurus site
        working-directory: pro
        run: npm run build

      - name: Generate candidate links
        working-directory: pro
        run: node generate_candidate_links.mjs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pro/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Discord Notification
        if: success()
        run: |
          # サイトのURLを通知するメッセージを作成
          SITE_URL="https://ootomonaiso.github.io/ootomonaiso_strage/"
          MESSAGE=":tada: **サイトが更新されました！** :tada:\n\n最新のサイトはこちら: [$SITE_URL]($SITE_URL)"

          # Discord Webhook で通知
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "'"$MESSAGE"'"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
